### ISSUE TITLE
document <sortingcode>

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#105]
This relates to #101.

\<sortingcode> is special in that we neither have documentation nor even an example for what this element is for.

**Comment by stpeter** [comment]
For context, this construct was defined in the Extensible Address Language spec (OASIS, 2002), as follows: 

"This is the sub-element of the element “PostalServiceElements”. This element can occur once and is optional. This element is required for sorting addresses. Values may for example be CEDEX 16 (France). This element provides the following attributes:
Type: Defines the type for the sorting code and is optional.
Code: Some postal services use a special code to define the element. Example: ECCMA Code Tables for postal services."

**Comment by reschke** [comment]
FWIW, I would really prefer to just remove all the address elements added after 7991, and to deprecate everything except postalLine.

**Comment by arusso-rpc** [comment]
Hm. Testing <sortingcode> to hold CEDEX as mentioned above yields this warning from xml2rfc (using an address from RFC 8968). 
```
 Warning: Postal address part filled in, but not used: <sortingcode>: CEDEX 13
 Available elements for France are: <extaddr>, <street>, <code>, <city>, <country>
```

**Comment by jrlevine** [comment]
France considers CEDEX to be a pseudo-city. I haven't been able to find any uses of <sortingcode>

**Comment by levkowetz** [comment]
I updated the codimd page yesterday to list the countries/territories that
the address internationalisation database currently recognises as using
sorting-code.  This may have changed since the copied text was written.

	Henrik

**Comment by jrlevine** [comment]
I see the list and I believe it is what the library says, but it makes no sense. Most of those are parts of France and use French addresses, yet France is not on the list. Something is broken.

**Comment by reschke** [comment]
(broken record alert) we are spending an incredibal amount of time to debug/rationalize/document a feature we really really do not need

**Comment by levkowetz** [comment]
On 2021-05-20 18:01, John L wrote:
> I see the list and I believe it is what the library says, but it
> makes no sense. Most of those are parts of France and use French
> addresses, yet France is not on the list. Something is broken.

No, all of those are separate territories, and yes, many of them have
been French colonies or are overseas French territories, but the do
*not* share the current French postal format.  I'd speculate that while
mainland France has moved away from sorting-code as a separate entry in
the postal format, the territories in question may very well have retained
an old postal address format that has kept the concept.

Since I know that changes in culture, administration, language, concepts
regularly originate in the capital city of reasonably well administered
societies (there's been research on this, even quantifying the time lag
between capital and rural areas as a function of distance in various time
periods) it doesn't surprise me at all that the overseas territories may
lag also with respect to postal address format.  Makes perfect sense to me.


	Henrik

**Comment by jrlevine** [comment]
The UPU, which really ought to know, says all the French territories use the same format. I have been to Martinique and Guadeloupe and Monaco (not part of France, but the posts are run by France) and know what the addresses look like.

**Comment by levkowetz** [comment]
Sounds like you should file a bug report on the google internationalization address format database, then.

**Comment by jrlevine** [comment]
> Sounds like you should file a bug report on the google internationalization address format database, then.
> […](#)

Good thought. I did.

**Comment by reschke** [comment]
> Good thought. I did.

Could you please link the ticket here?

**Comment by stpeter** [comment]
This appears to be overtaken by events.

**Comment by stpeter** [comment]
Closing because all postal issues will be addressed by https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis/issues/137 and related changes.
