### ISSUE TITLE
pn attribute

### ISSUE THREAD

**Issue by mnot** [rfc-format/draft-iab-xml2rfc-v3-bis#174]
The 2.32 revision of the schema changed the content of the `pn` attribute from text to an `xsd:ID`. This should be documented.

**Comment by stpeter** [comment]
It seems that the intent here might have been to disallow whitespace in the `pn` attribute, since the `pn` attribute is used in the same ways as the `anchor` attribute (but often auto-generated by tooling if the `anchor` attribute was not provided in the source file). But I agree that the change should be documented.

**Comment by jrlevine** [comment]
Sounds right, also makes it slightly clearer that pn's are supposed to be unique.

**Comment by levkowetz** [comment]
The uniqueness requirement was the primary reason for the change.  One of the validators I used during development actually complained about pn  not being xsd:ID ,:-)

**Comment by stpeter** [comment]
I suggest that we have consensus and this should be documented in 7991bis.

**Comment by stpeter** [comment]
@jrlevine Shall we close this (with the understanding that 7991bis will be updated as needed)? Whatever is best for your workflow...

**Comment by jrlevine** [comment]
OK with me

**Comment by jrlevine** [comment]
pn is in the RNG but is one of the generated elements excluded from the text. See #201
