### ISSUE TITLE
need "isCodeComponent" attribute

### ISSUE THREAD

**Issue by reschke** [rfc-format/draft-iab-xml2rfc-v3-bis#8]
(from https://tools.ietf.org/tools/xml2rfc/trac/ticket/322)

There should be a way to mark artwork/sourcecode to contain a "code component" in the sense of <​https://www.ietf.org/iesg/statement/copyright.html>, as proposed in <​https://greenbytes.de/tech/webdav/rfc2629xslt/rfc2629xslt.html#ext-rfc2629.artwork>.

**Comment by paulehoffman** [comment]
This should be in both \<artwork\> and \<sourcecode\>. However, this feature should first be discussed in the places that deal with IPR issues.

**Comment by levkowetz** [comment]
Letting `<artwork/>` and `<sourcecode/>` render without and with `<CODE STARTS>`, respectively, would have the advantage of being both intuitive and providing an option to avoid the `<CODE STARTS>` delimiter if explicitly not wanted.  If it is imperative to be able to use `<sourcecode/>` without the delimiter, we could add a flag to disable the rendering of the delimiter instead.  Having a flag to **enable** the delimiter within artwork seems like overdoing things a bit -- I'd prefer to leave artwork without that option, since it seems so intuitive to couple it to `<sourcecode/>`.

**Comment by paulehoffman** [comment]
The recent discussion on the list shows that <sourcecode> is useful for many things that do not want <CODE BEGINS> inserted, and that <CODE BEGINS> has certain legal meanings. Thus, I'm going to close this.

**Comment by paulehoffman** [comment]
That's good, because my answer was wrong. I misunderstood the request here. Reopening, and this issue should come to the list at some point.

**Comment by reschke** [comment]
See 

   https://tools.ietf.org/html/draft-levkowetz-xml2rfc-v3-implementation-notes-08#section-3.1.22

for Henrik's proposal.
